spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.37.130
    port: 5672
    username: guest
    password: guest
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul: # 拦截路径
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
  retryable: true 

#ribbon: 重试规则
#  ConnectTimeout: 1000
#  ReadTimeout: 1000
#  MaxAutoRetriesNextServer: 1
#  MaxAutoRetries: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
management: #仪表盘
  endpoints:
    web:
      exposure:
        include: hystrix.stream